### ISSUE TITLE
Rename vertical slabs

### ISSUE THREAD

**Issue by Tohricat** [Nyphet/just-vertical-slabs#11]
Hi. I'm in love with this mod! To make it easier to differentiate from slabs and vertical slabs, could vertical slabs be named 'Vertical Slabs' as opposed to solely 'Slabs'?

**Comment by Crystal-Spider** [comment]
Hi! Thank you for your words!  
Unfortunately I will not change the way Vertical Slabs are called for a simple reason: the way they are named now does not require any extra translation files, which would be quite impossible to have completed due to the main aim of this mod: adapting to any other mod.  
Since I cannot know in advance which other slabs are going to be included, I also cannot provide any translation without missing some. Naming Vertical Slabs the same as Horizontal Slabs makes my mod more adaptive, and fortunately Horizontal Slabs are just called Slabs, and technically speaking Vertical Slabs are slabs too.
