### ISSUE TITLE
[Request] Make full block from vertical slab

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [Nyphet/just-vertical-slabs#2]
Hi, first of all, this mod is incredibly awesome. 
As the title says, I cannot seem to be able to make a full block from vertical slabs just like you can do it with normal slabs, can you pls add this feature? also, recipe support for JEI would be excelent.
This mod definitely goes to my modpack.

**Comment by Crystal-Spider** [comment]
Hi! Let me thank you for all the kind words!  
About the features you asked for, they are my top 2 features in my TODO list, so rest assured that at some point they will be implemented.  
As of when, that's a good question. Unfortunately I don't have much time to focus on mod development and those two features are not that simple to implement.  
Most probably by the end of September I will have released them, along with porting this mod to 1.19.  
Why September? Because during summer I won't have to focus much on university and I can take a few weeks off work.

I will keep you updated about those two features, in the meantime thank you again!

**Comment by Crystal-Spider** [comment]
Okay, now that someone asked for it, I couldn't help but work a bit on this ahah  
So today I took some hours off my university studying and implemented double vertical slabs, aka full blocks from vertical slabs.  
I released a beta version ([1.18.2-3.2.0.0-beta1](https://github.com/Nyphet/just-vertical-slabs/releases/tag/v1.18.2-3.2.0.0-beta1)) with this feature.  
I hope you, and everyone else, can enjoy this version in the meantime that I focus on my upcoming exams!

**Comment by xXMolgadoGamer01Xx** [comment]
You're epic man!

**Comment by Crystal-Spider** [comment]
I will change a bit this issue to make it regard only double vertical slabs. This way I can add it to the v3.2.0.0 milestone and close it when it will be released.
For the JEI topic I created [this ](https://github.com/Nyphet/just-vertical-slabs/issues/7) other issue.

**Comment by Crystal-Spider** [comment]
I only need to fix issue #9 before releasing version 3.2.0.0.  
However I merged the branch with the code to solve this issue, so I'm closing this and soon version 3.2.0.0 will be released.
