### ISSUE TITLE
Crash at world loading/creating

### ISSUE THREAD

**Issue by agentwolf88** [Nyphet/just-vertical-slabs#20]
**Describe the bug**
Crash at world loading.

**Stacktrace and logs**
https://0x0.st/o1Dq.txt

**System information:**
 - OS:  macOS
 - Minecraft version: 1.18.2

**Comment by Crystal-Spider** [comment]
This crash is weird.  
I'd need you to list all the mods in your modpack that are adding slabs so that I can create a smaller modpack to reproduce the issue and understand whether it's an issue with my mod or with some other mod.

To be honest I can come up with a fix, but given the crash you provided fixing it as I'm thinking right now would mean to have one or more slabs without the proper crafting recipes.  
Do you know if there's any mod that is adding slabs that can't be crafted or that can be crafted but have some weird recipe?

**Comment by agentwolf88** [comment]
Can i upload my modpack on dropbox for you? Would that help?

**Comment by Crystal-Spider** [comment]
Not much to be honest. Did you create the modpack yourself or did you download it from somewhere?  
If it's not the latter, do you know which mods add new slabs?

**Comment by agentwolf88** [comment]
Its my own modpack. I do not know exactly which mod is adding slabs. I try some mods one by one and tell you which mod is the problem.

**Comment by Crystal-Spider** [comment]
If you're using CurseForge you can export your modpack, attach it here and then I can download and test it out.

**Comment by agentwolf88** [comment]
The problem is a Mekanism Addon.

https://www.curseforge.com/minecraft/mc-mods/mekanism-additions

With Mekanism + Mekanism Additions + Just Vertical sSlabs the game crashs at world create/load.

**Comment by Crystal-Spider** [comment]
Okay, I should have fixed the issue and I will release a new version soon.

**Comment by Crystal-Spider** [comment]
Reopen the issue if you find any other incorrect behavior, I'm closing this now.  
[Release 1.18.2-3.2.0.2](https://github.com/Nyphet/just-vertical-slabs/releases/tag/v1.18.2-3.2.0.2) is already available to download from Curseforge.
