### ISSUE TITLE
Vertical Slabs not showing up in JEI or Creative menu

### ISSUE THREAD

**Issue by LordCodFish** [Nyphet/just-vertical-slabs#25]
**Describe the bug**

Vertical slabs disappearing from both the creative menu and JEI on Creative Server

**To Reproduce**
1. Join multiplayer server
2.  Check creative tab and JEI for slabs
3. Find none

**Expected behavior**

I expected to open the creative menu and pull a slab out to start building with

**Screenshots**

![image](https://user-images.githubusercontent.com/97019088/199553560-633fd71d-8508-47f5-ad6a-f69ce518115b.png)
![image](https://user-images.githubusercontent.com/97019088/199553576-df1e2a38-40a2-45e1-9268-b14d5c39c4af.png)

**Stacktrace and logs**
If applicable, copy and paste relevant logs.

**System information:**
 - OS:  Windows 11
 - Minecraft version: 1.19.2
 - Release version: 4.0.0.0
 - Other mods installed that add slabs: Quark, CreateDeco

**Additional context**

Restarting the server usually causes them to show up again, but I'd still like to report it regardless, seeing as it is a bug

**Comment by Crystal-Spider** [comment]
JEI does not work because of how recipes are registered (kind of the same reason why you can't see dyed leather armors). It will be fixed in a future release, keep an eye on #7 for progress.  
Searching in the creative menu for "vertical" won't show any vertical slabs because they do not have "vertical" in their name, you should search for just "slab" to find all possible vertical slabs. It is still possible that joining a server will result in the creative search tab to not show vertical slabs regardless of your search input, in such case you can use the dedicated vertical slab creative tab to get any vertical slab you want.  
Let me know if you experience further issues.
